# Analyse les résultats des métriques d'évaluation

In [1]:
import pandas as pd
import numpy as np

In [2]:
csv = "/tempory/21234701/blast_cluster_validation_scores.csv"

df = pd.read_csv(csv)

## Statistiques globales

In [3]:
df.head()

,cluster_id,co_distance,dunn_index,cut,ncut,nb_nodes,nb_edges
0,C0_245,12412.146069,0.0,51.778304,0.002081,72924,36354
1,C0_16,65993.505760,0.0,1545.810756,0.011576,259122,127066
2,C0_1841,224.456057,0.0,0.730413,0.001624,974,485
3,Comp_63841,0.414400,0.0,0.000000,0.000000,2,1
4,Comp_5748,14.619036,0.0,0.000000,0.000000,52,26

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 142629 entries, 0 to 142628
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   cluster_id   142629 non-null  str
 1   co_distance  142629 non-null  float64
 2   dunn_index   142629 non-null  float64
 3   cut          142629 non-null  float64
 4   ncut         142629 non-null  float64
 5   nb_nodes     142629 non-null  int64
 6   nb_edges     142629 non-null  int64
dtypes: float64(4), int64(2), str(1)
memory usage: 7.6 MB

In [5]:
df.describe()

,co_distance,dunn_index,cut,ncut,nb_nodes,nb_edges
count,142629.000000,142629.0,142629.000000,142629.000000,142629.000000,142629.000000
mean,165.934868,0.0,1.760482,0.000061,684.418190,338.940117
std,2014.588111,0.0,36.333635,0.000596,8569.344378,4226.115770
min,0.100037,0.0,0.000000,0.000000,2.000000,1.000000
25%,0.584494,0.0,0.000000,0.000000,2.000000,1.000000
50%,0.984000,0.0,0.000000,0.000000,2.000000,1.000000
75%,2.916598,0.0,0.000000,0.000000,10.000000,5.000000
max,168246.330580,0.0,5147.802167,0.025020,603388.000000,299561.000000

In [13]:
print(df.describe().to_latex(index=False, formatters={"name": str.upper}, float_format="{:.6f}".format,))

\begin{tabular}{rrrrrr}
\toprule
co_distance & dunn_index & cut & ncut & nb_nodes & nb_edges \\
\midrule
142629.000000 & 142629.000000 & 142629.000000 & 142629.000000 & 142629.000000 & 142629.000000 \\
165.934868 & 0.000000 & 1.760482 & 0.000061 & 684.418190 & 338.940117 \\
2014.588111 & 0.000000 & 36.333635 & 0.000596 & 8569.344378 & 4226.115770 \\
0.100037 & 0.000000 & 0.000000 & 0.000000 & 2.000000 & 1.000000 \\
0.584494 & 0.000000 & 0.000000 & 0.000000 & 2.000000 & 1.000000 \\
0.984000 & 0.000000 & 0.000000 & 0.000000 & 2.000000 & 1.000000 \\
2.916598 & 0.000000 & 0.000000 & 0.000000 & 10.000000 & 5.000000 \\
168246.330580 & 0.000000 & 5147.802167 & 0.025020 & 603388.000000 & 299561.000000 \\
\bottomrule
\end{tabular}

## Statistiques sans les clusters à moins de 5 nœuds

In [7]:
df_new = df[df['nb_nodes'] > 5]
df_new.describe()

,co_distance,dunn_index,cut,ncut,nb_nodes,nb_edges
count,57558.000000,57558.0,57558.000000,57558.000000,57558.000000,57558.000000
mean,410.176975,0.0,4.362483,0.000151,1692.704680,838.251798
std,3155.508041,0.0,57.096222,0.000931,13426.329943,6621.159884
min,0.316607,0.0,0.000000,0.000000,6.000000,3.000000
25%,2.245128,0.0,0.000000,0.000000,6.000000,3.000000
50%,4.263438,0.0,0.000000,0.000000,12.000000,6.000000
75%,12.125990,0.0,0.000000,0.000000,44.000000,22.000000
max,168246.330580,0.0,5147.802167,0.025020,603388.000000,299561.000000

In [14]:
print(df_new.describe().to_latex(index=False, formatters={"name": str.upper}, float_format="{:.6f}".format,))

\begin{tabular}{rrrrrr}
\toprule
co_distance & dunn_index & cut & ncut & nb_nodes & nb_edges \\
\midrule
57558.000000 & 57558.000000 & 57558.000000 & 57558.000000 & 57558.000000 & 57558.000000 \\
410.176975 & 0.000000 & 4.362483 & 0.000151 & 1692.704680 & 838.251798 \\
3155.508041 & 0.000000 & 57.096222 & 0.000931 & 13426.329943 & 6621.159884 \\
0.316607 & 0.000000 & 0.000000 & 0.000000 & 6.000000 & 3.000000 \\
2.245128 & 0.000000 & 0.000000 & 0.000000 & 6.000000 & 3.000000 \\
4.263438 & 0.000000 & 0.000000 & 0.000000 & 12.000000 & 6.000000 \\
12.125990 & 0.000000 & 0.000000 & 0.000000 & 44.000000 & 22.000000 \\
168246.330580 & 0.000000 & 5147.802167 & 0.025020 & 603388.000000 & 299561.000000 \\
\bottomrule
\end{tabular}